### ISSUE TITLE
你数据库文件呢？

### ISSUE THREAD

**Issue by gywei** [ctrlcommunity/ASP.NET-Core-BaseDesign#15]
你数据库文件呢？
什么都不给，让人怎么运行？

**Comment by hueifeng** [comment]
我附加一下

**Comment by gywei** [comment]
这个数据库脚本不全。还有存储过程呢也少了。。。好多错误、、、

**Comment by gywei** [comment]
> 我附加一下

这个数据库脚本不全。还有存储过程呢也少了。。。好多错误、、、

**Comment by hueifeng** [comment]
> > 我附加一下
> 
> 这个数据库脚本不全。还有存储过程呢也少了。。。好多错误、、、

表结构是完整的，该框架未使用存储过程 ，请检查执行sql方式是否正确

**Comment by gywei** [comment]
> > > 我附加一下
> > 
> > 
> > 这个数据库脚本不全。还有存储过程呢也少了。。。好多错误、、、
> 
> 表结构是完整的，该框架未使用存储过程 ，请检查执行sql方式是否正确



Msg 102, Level 15, State 6, Line 10
Incorrect syntax near 'CATALOG_COLLATION'.
Msg 15048, Level 16, State 1, Line 12
Valid values of the database compatibility level are 100, 110, or 120.
Msg 911, Level 16, State 4, Line 16
Database 'Ctrl.Net' does not exist. Make sure that the name is entered correctly.
Msg 5011, Level 14, State 5, Line 19
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 19
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 21
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 21
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 23
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 23
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 25
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 25
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 27
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 27
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 29
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 29
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 31
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 31
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 33
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 33
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 35
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 35
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 37
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 37
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 39
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 39
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 41
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 41
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 43
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 43
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 45
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 45
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 47
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 47
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 49
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 49
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 51
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 51
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 53
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 53
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 55
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 55
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 57
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 57
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 59
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 59
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 61
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 61
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 63
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 63
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 65
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 65
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 67
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 67
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 69
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 69
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 71
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 71
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 73
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 73
ALTER DATABASE statement failed.
Msg 5011, Level 14, State 5, Line 75
User does not have permission to alter database 'Ctrl.Net', the database does not exist, or the database is not in a state that allows access checks.
Msg 5069, Level 16, State 1, Line 75
ALTER DATABASE statement failed.
Msg 102, Level 15, State 29, Line 77
Incorrect syntax near 'QUERY_STORE'.
Msg 911, Level 16, State 1, Line 79
Database 'Ctrl.Net' does not exist. Make sure that the name is entered correctly.
Msg 155, Level 15, State 1, Line 105
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 127
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 146
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 165
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 186
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 215
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 233
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 257
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 284
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 305
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 336
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 356
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 2714, Level 16, State 6, Line 364
There is already an object named 'Sys_Permission' in the database.
Msg 2714, Level 16, State 6, Line 377
There is already an object named 'Sys_PermissionUser' in the database.
Msg 155, Level 15, State 1, Line 405
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 426
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.
Msg 155, Level 15, State 1, Line 451
'OPTIMIZE_FOR_SEQUENTIAL_KEY' is not a recognized CREATE TABLE option.

**Comment by hueifeng** [comment]
> > > > 我附加一下
> > > 
> > > 
> > > 这个数据库脚本不全。还有存储过程呢也少了。。。好多错误、、、
> > 
> > 
> > 表结构是完整的，该框架未使用存储过程，请检查执行sql方式是否正确
> 
> 消息102，级别15，状态6，第10行
> 'CATALOG_COLLATION'附近的语法不正确。
> 消息15048，级别16，状态1，行12
> 数据库兼容级别的有效值为100、110或120。
> 消息911，级别16，状态4，行16
> 数据库'Ctrl.Net'不存在。确保正确输入名称。
> 消息5011，级别14，状态5，行19
> 用户无权更改数据库Ctrl.Net，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第19行
> ALTER DATABASE语句失败。
> Msg 5011，第14级，状态5，第21行
> 用户无权更改数据库Ctrl.Net，该数据库不存在或该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第21行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第23行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第23行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第25行
> 用户无权更改数据库'Ctrl.Net'，数据库不存在，或者数据库未处于允许访问检查的状态。
> Msg 5069，第16级，状态1，第25行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第27行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第27行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第29行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第29行
> ALTER DATABASE语句失败。
> Msg 5011，第14级，状态5，第31行
> 用户无权更改数据库Ctrl.Net，该数据库不存在或该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第31行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第33行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第33行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第35行
> 用户无权更改数据库'Ctrl.Net'，数据库不存在，或者数据库未处于允许访问检查的状态。
> 讯息5069，第16级，州1，第35行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第37行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第37行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第39行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第39行
> ALTER DATABASE语句失败。
> 讯息5011，第14级，州立5，第41行
> 用户无权更改数据库Ctrl.Net，该数据库不存在或该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第41行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第43行
> 用户无权更改数据库Ctrl.Net，该数据库不存在或该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第43行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第45行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，第16级，州1，第45行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第47行
> 用户无权更改数据库Ctrl.Net，数据库不存在或数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第47行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第49行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第49行
> ALTER DATABASE语句失败。
> 讯息5011，第14级，州立5，第51行
> 用户无权更改数据库Ctrl.Net，该数据库不存在或该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第51行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第53行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第53行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，行55
> 用户无权更改数据库Ctrl.Net，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 讯息5069，第16级，州1，第55行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第57行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第57行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第59行
> 用户没有权限更改数据库'Ctrl.Net'，或者该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第59行
> ALTER DATABASE语句失败。
> 讯息5011，第14级，州立5，第61行
> 用户无权更改数据库Ctrl.Net，该数据库不存在或该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第61行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第63行
> 用户无权更改数据库'Ctrl.Net'，数据库不存在，或者数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第63行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第65行
> 用户没有权限更改数据库'Ctrl.Net'，或者该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 讯息5069，第16级，州1，第65行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第67行
> 用户没有权限更改数据库'Ctrl.Net'，或者该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第67行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第69行
> 用户无权更改数据库Ctrl.Net，数据库不存在或数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第69行
> ALTER DATABASE语句失败。
> Msg 5011，第14级，状态5，第71行
> 用户无权更改数据库Ctrl.Net，该数据库不存在或该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第71行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第73行
> 用户没有更改数据库'Ctrl.Net'的权限，该数据库不存在，或者该数据库未处于允许访问检查的状态。
> 消息5069，级别16，状态1，第73行
> ALTER DATABASE语句失败。
> 消息5011，级别14，状态5，第75行
> 用户没有权限更改数据库'Ctrl.Net'，或者该数据库不存在，或者该数据库未处于允许访问检查的状态。
> Msg 5069，第16级，状态1，第75行
> ALTER DATABASE语句失败。
> 消息102，级别15，状态29，第77
> 行在“ QUERY_STORE”附近的语法不正确。
> 消息911，级别16，状态1，行79
> 数据库'Ctrl.Net'不存在。确保正确输入名称。
> 消息155，级别15，状态1，行
> 105'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 127'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 146'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 165'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 186'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 215'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 233'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 257'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 284'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 305'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 讯息155，层15
> 'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 356'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息2714，级别16，状态6，行364
> 数据库中已经存在一个名为“ Sys_Permission”的对象。
> 消息2714，级别16，状态6，行377
> 数据库中已经有一个名为“ Sys_PermissionUser”的对象。
> 消息155，级别15，状态1，行
> 405'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，级别15，状态1，行
> 426'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。
> 消息155，第15级，州1，行451
> 'OPTIMIZE_FOR_SEQUENTIAL_KEY'不是公认的CREATE TABLE选项。

Database 'Ctrl.Net' does not exist. Make sure that the name is entered correctly.
你从你本地创建数据库，创建完成后再将数据库文件创建数据库的sql删掉，SqlServer管理工具中一定要选择你刚创建的数据库，然后执行下面语句，切记只是删除sql文件中的创建database sql
